### ISSUE TITLE
loop dict assignment rewrite

### ISSUE THREAD

**Issue by joaomcteixeira** [julie-forman-kay-lab/IDPConformerGenerator#222]
hi @menoliu , looking to the code below, 

https://github.com/julie-forman-kay-lab/IDPConformerGenerator/blob/77a29644a1a907f21ddd93eb5757ba8ae1bbe305/src/idpconfgen/cli_sscalc.py#L298-L308

it looks like we can rewrite it to the code below because `ss` is the same as in key.

```python
for ss in dssp_data[conf]["dssp"]:
    frac_dssp[ss][r] += p[c]
```

Since this is your addition, I invite you to go forward with the rewrite :+1: I think there are likely similar parts in the repository. Have a look. :wink:

**Comment by menoliu** [comment]
Good catch! Yeah all of those `elifs` look daunting, I will see to it
