### ISSUE TITLE
Chains that don't need to be modeled throw error in multi-chain complexes

### ISSUE THREAD

**Issue by benjbuch** [julie-forman-kay-lab/IDPConformerGenerator#269]
If the sequence in the pdb and the mapped fasta sequence are identical, an index out of range error is thrown. Most likely, because a sub-routine tries to generate conformers.

```
Traceback (most recent call last):
  File "miniforge3/envs/idpconfgen/bin/idpconfgen", line 33, in <module>
    sys.exit(load_entry_point('idpconfgen', 'console_scripts', 'idpconfgen')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "IDPConformerGenerator/src/idpconfgen/cli.py", line 142, in maincli
    cmd.func(**vars(cmd))
  File "IDPConformerGenerator/src/idpconfgen/cli_ldrs.py", line 637, in main
    DISORDER_BOUNDS[chain] = consecutive_grouper(disordered_res)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "IDPConformerGenerator/src/idpconfgen/ldrs_helper.py", line 145, in consecutive_grouper
    grouped = [[seq[0]]]
                ~~~^^^
IndexError: list index out of range
```

The expected behavior would probably be to skip modeling the chain with a warning. (Or likewise this is an opportunity to skip some parts if there are less than X residues?)

**Comment by benjbuch** [comment]
A work-around is to clip the PDB file by three or four residues and have them modeled.

**Comment by menoliu** [comment]
Thanks @benjbuch for catching this bug, you are correct, any perfectly matching sequences-to-PDB should not be modelled and skipped.

I will see to this at my earliest convenience!

**Comment by formankay** [comment]
Thanks!
________________________________

**Comment by benjbuch** [comment]
Thank you, @menoliu!
